spring.application.name=smartlock-server
# Cấu hình cổng chạy Server
server.port=8080

# Cấu hình H2 Database
spring.datasource.url=jdbc:h2:mem:smartlockdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Tự động tạo bảng dựa trên code Java
spring.jpa.hibernate.ddl-auto=update